### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by woongjae-yoo** [cevans01/gr-adaptive#1]
hello, I appreciate for your effort on this module
but I'm on installation issue (ubuntu 20.14)

when I run  'cmake ..' command,
I got policy CMP0012 error.
my CMAKE version is 3.16.3

it it well known issue?

below is part of cmake error message. thank you.

> 
CMake Warning (dev) at /usr/lib/x86_64-linux-gnu/cmake/gnuradio/GnuradioConfig.cmake:35 (if):
  if given arguments:

    "ON"

  An argument named "ON" appears in a conditional statement.  Policy CMP0012
  is not set: if() recognizes numbers and boolean constants.  Run "cmake
  --help-policy CMP0012" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.
Call Stack (most recent call first):
  CMakeLists.txt:119 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in /usr/lib/x86_64-linux-gnu/cmake/gnuradio/GnuradioConfig.cmake:
  Policy CMP0011 is not set: Included scripts do automatic cmake_policy PUSH
  and POP.  Run "cmake --help-policy CMP0011" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  The included script

    /usr/lib/x86_64-linux-gnu/cmake/gnuradio/GnuradioConfig.cmake

  affects policy settings.  CMake is implying the NO_POLICY_SCOPE option for
  compatibility, so the effects are applied to the including context.
Call Stack (most recent call first):
  CMakeLists.txt:119 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at CMakeLists.txt:122 (message):
  CppUnit required to compile adaptive

-- Configuring incomplete, errors occurred!
See also "/home/woongjae/gr-adaptive/build/CMakeFiles/CMakeOutput.log".
See also "/home/woongjae/gr-adaptive/build/CMakeFiles/CMakeError.log".

>

**Comment by cevans01** [comment]
Hi! I appreciate your interest in the package. Unfortunately, I'm not maintaining this package and I don't know what state it's in (if it compiles or works). This was mostly some experimentation code I wrote several years ago.
